"""Adds users table, removes username from user_activity

Revision ID: 25f1a6f4b020
Revises: 75c9a8f2f225
Create Date: 2018-10-15 21:18:48.631778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25f1a6f4b020'
down_revision = '75c9a8f2f225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('first_name', sa.String(), nullable=True),
        sa.Column('last_name', sa.String(), nullable=True),
        sa.Column('username', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('user_activity', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_activity', sa.Column('username', sa.VARCHAR(), nullable=True))
    op.drop_table('users')
    # ### end Alembic commands ###
